
exports.up = knex => {
  return knex.schema.createTable('sample', t => {
    t.specificType('id', 'int generated by default as identity primary key')
    t.text('template').defaultTo('')
    t.dateTime('created').defaultTo(knex.fn.now())
  })
}

exports.down = knex => {
  return knex.schema.dropTable('sample')
}
